name: Metrics embed
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write
    steps:
    - uses: lowlighter/metrics@v3.34
      with:
        base_indepth: yes
        # Show `Available for hire!` in header section
        base_hireable: yes
        base_skip: no
        repositories_forks: yes
        repositories_affiliations: owner, collaborator, organization_member
        # Default skipped repositories
        # repositories_skipped: # optional, default is <default-val>
        # GitHub Personal Access Token
        token: ${{ secrets.METRICS_TOKEN }}
        user: ishaan-kapoor
        # GitHub repository
        # repo: # optional, default is <default-value>
        # GitHub Token used to commit metrics
        # committer_token: # optional, default is ${{ github.token }}
        # Target branch
        # committer_branch: # optional, default is <default-value>
        # Commit message
        # committer_message: # optional, default is <default-value>
        # Gist id
        # committer_gist: # optional, default is <default-value>
        # Output path
        # filename: # optional, default is <default-value>
        # Markdown template path
        # markdown: # optional, default is <default-value>
        # Markdown file cache
        # markdown_cache: # optional, default is <default-value>
        # Output action
        # output_action: # optional, default is <default-value>
        # Output condition
        # output_condition: # optional, default is <default-value>
        # Optimization features
        # optimize: # optional, default is <default-value>
        # Community templates to setup
        # setup_community_templates: # optional, default is <default-value>
        # Template
        # template: # optional, default is <default-value>
        # Query parameters
        # query: # optional, default is <default-value>
        # Extra CSS
        # extras_css: # optional, default is <default-value>
        # Extra JavaScript
        # extras_js: # optional, default is <default-value>
        # GitHub REST API endpoint
        # github_api_rest: # optional, default is <default-value>
        # GitHub GraphQL API endpoint
        # github_api_graphql: # optional, default is <default-value>
        # Timezone for dates
        config_timezone: IST
        # Plugin order
        # config_order: # optional, default is <default-value>
        # Use twemojis
        # config_twemoji: # optional, default is <default-value>
        # Use GitHub custom emojis
        # config_gemoji: # optional, default is <default-value>
        # Use GitHub octicons
        # config_octicon: # optional, default is <default-value>
        # Display width (for image output formats)
        # config_display: # optional, default is <default-value>
        # Use CSS animations
        # config_animations: # optional, default is <default-value>
        # Base64-encoded images
        # config_base64: # optional, default is <default-value>
        # Output padding
        # config_padding: # optional, default is <default-value>
        # Output format
        # config_output: # optional, default is <default-value>
        # Configuration presets
        # config_presets: # optional, default is 
        # Retries in case of failures (for rendering)
        # retries: # optional, default is <default-value>
        # Delay between each retry (in seconds, for rendering)
        # retries_delay: # optional, default is <default-value>
        # Retries in case of failures (for output action)
        # retries_output_action: # optional, default is <default-value>
        # Delay between each retry (in seconds, for output action)
        # retries_delay_output_action: # optional, default is <default-value>
        # Clean previous workflows jobs
        # clean_workflows: # optional, default is <default-value>
        # Job delay
        # delay: # optional, default is <default-value>
        # Minimum GitHub REST API requests quota required to run
        # quota_required_rest: # optional, default is <default-value>
        # Minimum GitHub GraphQL API requests quota required to run
        # quota_required_graphql: # optional, default is <default-value>
        # Minimum GitHub Search API requests quota required to run
        # quota_required_search: # optional, default is <default-value>
        # Notice about new releases of metrics
        # notice_releases: # optional, default is <default-value>
        # Use pre-built docker image from [GitHub container registry](https://github.com/lowlighter/metrics/pkgs/container/metrics)
        # use_prebuilt_image: # optional, default is true
        # Fatal plugin errors
        # plugins_errors_fatal: # optional, default is <default-value>
        # Debug mode
        # debug: # optional, default is <default-value>
        # SVG validity check
        # verify: # optional, default is <default-value>
        # Debug flags
        # debug_flags: # optional, default is <default-value>
        # Print output in console
        # debug_print: # optional, default is <default-value>
        # Dry-run
        # dryrun: # optional, default is <default-value>
        # Experimental features
        # experimental_features: # optional, default is <default-value>
        # Use mocked data instead of live APIs
        # use_mocked_data: # optional, default is <default-value>
        plugin_isocalendar: yes
        plugin_isocalendar_duration: full-year
        plugin_languages: yes
        # plugin_languages_ignored: # optional, default is <default-value>
        # plugin_languages_skipped: # optional, default is <default-value>
        plugin_languages_limit: 25
        # plugin_languages_threshold: # optional, default is <default-value>
        plugin_languages_other: no
        # plugin_languages_colors: # optional, default is <default-value>
        # plugin_languages_aliases: # optional, default is <default-value>
        plugin_languages_sections: mostly-used
        plugin_languages_details: bytes-size, lines
        plugin_languages_indepth: yes

        plugin_stargazers: no
        # plugin_stargazers_days: # optional, default is <default-value>
        # plugin_stargazers_charts: # optional, default is <default-value>
        # plugin_stargazers_charts_type: # optional, default is <default-value>
        # plugin_stargazers_worldmap: # optional, default is <default-value>
        # plugin_stargazers_worldmap_token: # optional, default is <default-value>
        # plugin_stargazers_worldmap_sample: # optional, default is <default-value>
        plugin_lines: no
        # plugin_lines_skipped: # optional, default is <default-value>
        # plugin_lines_sections: # optional, default is <default-value>
        # plugin_lines_repositories_limit: # optional, default is <default-value>
        # plugin_lines_history_limit: # optional, default is <default-value>
        # plugin_lines_delay: # optional, default is <default-value>
        plugin_topics: no
        # plugin_topics_mode: mastered
        # plugin_topics_sort: random
        # plugin_topics_limit: 20
        # plugin_stars: no
        # plugin_stars_limit: # optional, default is <default-value>
        # plugin_licenses: no
        # plugin_licenses_setup: # optional, default is <default-value>
        # plugin_licenses_ratio: # optional, default is <default-value>
        # plugin_licenses_legal: # optional, default is <default-value>
        # plugin_habits: no
        # plugin_habits_from: # optional, default is <default-value>
        # plugin_habits_skipped: # optional, default is <default-value>
        # plugin_habits_days: # optional, default is <default-value>
        # plugin_habits_facts: # optional, default is <default-value>
        # plugin_habits_charts: # optional, default is <default-value>
        # plugin_habits_charts_type: # optional, default is <default-value>
        # plugin_habits_trim: # optional, default is <default-value>
        # plugin_habits_languages_limit: # optional, default is <default-value>
        # plugin_habits_languages_threshold: # optional, default is <default-value>
        plugin_contributors: no
        # plugin_contributors_base: # optional, default is <default-value>
        # plugin_contributors_head: # optional, default is <default-value>
        # plugin_contributors_ignored: # optional, default is <default-value>
        # plugin_contributors_contributions: # optional, default is <default-value>
        # plugin_contributors_sections: # optional, default is <default-value>
        # plugin_contributors_categories: # optional, default is <default-value>
        plugin_followup: no
        # plugin_followup_sections: # optional, default is <default-value>
        # plugin_followup_indepth: # optional, default is <default-value>
        # plugin_followup_archived: # optional, default is <default-value>
        plugin_reactions: no
        # plugin_reactions_limit: # optional, default is <default-value>
        # plugin_reactions_limit_issues: # optional, default is <default-value>
        # plugin_reactions_limit_discussions: # optional, default is <default-value>
        # plugin_reactions_limit_discussions_comments: # optional, default is <default-value>
        # plugin_reactions_days: # optional, default is <default-value>
        # plugin_reactions_display: # optional, default is <default-value>
        # plugin_reactions_details: # optional, default is <default-value>
        # plugin_reactions_ignored: # optional, default is <default-value>
        plugin_people: no
        # plugin_people_limit: # optional, default is <default-value>
        # plugin_people_identicons: # optional, default is <default-value>
        # plugin_people_identicons_hide: # optional, default is <default-value>
        # plugin_people_size: # optional, default is <default-value>
        # plugin_people_types: # optional, default is <default-value>
        # plugin_people_thanks: # optional, default is <default-value>
        # plugin_people_sponsors_custom: # optional, default is <default-value>
        # plugin_people_shuffle: # optional, default is <default-value>
        plugin_sponsorships: no
        # plugin_sponsorships_sections: # optional, default is <default-value>
        # plugin_sponsorships_size: # optional, default is <default-value>
        # plugin_sponsors: # optional, default is <default-value>
        # plugin_sponsors_sections: # optional, default is <default-value>
        # plugin_sponsors_past: # optional, default is <default-value>
        # plugin_sponsors_size: # optional, default is <default-value>
        # plugin_sponsors_title: # optional, default is <default-value>
        plugin_repositories: no
        # plugin_repositories_featured: # optional, default is <default-value>
        # plugin_repositories_pinned: # optional, default is <default-value>
        # plugin_repositories_starred: # optional, default is <default-value>
        # plugin_repositories_random: # optional, default is <default-value>
        # plugin_repositories_order: # optional, default is <default-value>
        # plugin_repositories_forks: # optional, default is <default-value>
        # plugin_repositories_affiliations: # optional, default is <default-value>
        plugin_discussions: no
        # plugin_discussions_categories: # optional, default is <default-value>
        # plugin_discussions_categories_limit: # optional, default is <default-value>
        plugin_starlists: no
        # plugin_starlists_limit: # optional, default is <default-value>
        # plugin_starlists_limit_repositories: # optional, default is <default-value>
        # plugin_starlists_languages: # optional, default is <default-value>
        # plugin_starlists_limit_languages: # optional, default is <default-value>
        # plugin_starlists_languages_ignored: # optional, default is <default-value>
        # plugin_starlists_languages_aliases: # optional, default is <default-value>
        # plugin_starlists_shuffle_repositories: # optional, default is <default-value>
        # plugin_starlists_ignored: # optional, default is <default-value>
        # plugin_starlists_only: # optional, default is <default-value>
        plugin_calendar: no
        # plugin_calendar_limit: 0
        plugin_achievements: no
        # plugin_achievements_threshold: # optional, default is <default-value>
        # plugin_achievements_secrets: # optional, default is <default-value>
        # plugin_achievements_display: # optional, default is <default-value>
        # plugin_achievements_limit: # optional, default is <default-value>
        # plugin_achievements_ignored: # optional, default is <default-value>
        # plugin_achievements_only: # optional, default is <default-value>
        plugin_notable: no
        # plugin_notable_filter: # optional, default is <default-value>
        # plugin_notable_skipped: # optional, default is <default-value>
        # plugin_notable_from: # optional, default is <default-value>
        # plugin_notable_repositories: # optional, default is <default-value>
        # plugin_notable_indepth: # optional, default is <default-value>
        # plugin_notable_types: # optional, default is <default-value>
        # plugin_notable_self: # optional, default is <default-value>
        plugin_activity: yes
        plugin_activity_limit: 1
        # plugin_activity_load: # optional, default is <default-value>
        # plugin_activity_days: # optional, default is <default-value>
        plugin_activity_visibility: public
        # Events timestamps
        plugin_activity_timestamps: no
        # plugin_activity_skipped: # optional, default is <default-value>
        # plugin_activity_ignored: # optional, default is <default-value>
        # plugin_activity_filter: # optional, default is <default-value>
        plugin_traffic: yes
        # plugin_traffic_skipped: # optional, default is <default-value>
        plugin_code: no
        # plugin_code_lines: # optional, default is <default-value>
        # plugin_code_load: # optional, default is <default-value>
        # plugin_code_days: # optional, default is <default-value>
        # plugin_code_visibility: # optional, default is <default-value>
        # plugin_code_skipped: # optional, default is <default-value>
        # plugin_code_languages: # optional, default is <default-value>
        plugin_gists: no
        plugin_projects: no
        # plugin_projects_limit: # optional, default is <default-value>
        # plugin_projects_repositories: # optional, default is <default-value>
        # plugin_projects_descriptions: # optional, default is <default-value>
        plugin_introduction: no
        # plugin_introduction_title: # optional, default is <default-value>
        plugin_wakatime: yes
        plugin_wakatime_token: ${{ secrets.WAKATIME_KEY }}
        plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, editors-graphs, os, os-graphs
        plugin_wakatime_days: 365
        plugin_wakatime_limit: 7
        plugin_wakatime_repositories_visibility: all
        plugin_leetcode: yes
        plugin_leetcode_user: ishaan-kapoor
        plugin_leetcode_sections: solved, skills, recent
        plugin_leetcode_limit_skills: 15
        plugin_leetcode_ignored_skills: fundamental
        plugin_leetcode_limit_recent: 1
